eog Input/11.png Target/11.png
eog Input/12.png Target/12.png
eog Input/13.png Target/13.png
eog Input/14.png Target/14.png
eog Input/15.png Target/15.png
eog Input/16.png Target/16.png
eog Input/17.png Target/17.png
eog Input/18.png Target/18.png
eog Input/19.png Target/19.png
eog Input/0.png  Target/0.png
eog Input/1.png  Target/1.png
eog Input/2.png  Target/2.png
eog Input/3.png  Target/3.png
eog Input/4.png  Target/4.png
eog Input/5.png  Target/5.png
eog Input/6.png  Target/6.png
eog Input/7.png  Target/7.png
eog Input/8.png  Target/8.png
eog Input/9.png  Target/9.png
